version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 9090:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: odontoeasy_dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
